import type { Metadata } from "next";
import { Preahvihear } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import WhatsappButton from "@/components/web/WhatsappButton";

const preahvihear = Preahvihear({
  subsets: ["latin"],
  weight: "400", // Preahvihear only has 400
  variable: "--font-preahvihear",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${preahvihear.className} antialiased`}>
        {children}
          <Toaster/>
             <WhatsappButton 
          phoneNumber="01614793657"
          message="Hi, I want to chat with you!" 
        />
      </body>
    </html>
  );
}
